name: Release Funtuna
on:
  workflow_dispatch:

jobs:
  Repack_and_Release:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.2.0
    steps:
    
    - name: Install dependencies
      run: |
        apk add build-base git zip p7zip
        apk add --no-cache gcompat

    - name: checkout code for release
      uses: actions/checkout@v1
    
    - name: build installer
      run: |
        cd installer
        make clean
        make

    - name: Zip Folder
      run: |
        TARGET=YoshiBoot_Fortuna_Installer.7z
        echo TARGET is $TARGET
        7z a -t7z -r $TARGET *
        ls -R 

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v7
      with:
        name: FunTuna
        path: |
             installer/YoshiBoot_Fortuna_Installer.ELF
