name: Release Funtuna
on:
  workflow_dispatch:

jobs:
  Repack_and_Release:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.2.0
    steps:
    
    - name: Install dependencies
      run: |
        apk add build-base git zip p7zip

    - name: checkout code for release
      uses: actions/checkout@v1
    
    - name: build installer
      run: |
        cd installer
        make clean
        make

    - name: prepare Release package
      run: |
        SCH=${GITHUB_SHA::7}
        cp installer/Installer.elf __Release/YoshiBoot_Fortuna_Installer.ELF

    - name: Zip Folder
      run: |
        SCH=${GITHUB_SHA::7}
        cd __Release
        echo commit $SCH >>commit.txt
        TARGET=YoshiBoot_Fortuna_Installer.7z
        echo TARGET is $TARGET
        7z a -t7z -r $TARGET *
        ls -R 

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: FunTuna
        path: |
             __Release/*.7z
             installer/YoshiBoot_Fortuna_Installer.ELF
